export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'

export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_GET_PROFILE_REQUEST = 'USER_GET_PROFILE_REQUEST'

export const USER_GET_PROFILE_SUCCESS = 'USER_GET_PROFILE_SUCCESS'

export const USER_GET_PROFILE_FAIL = 'USER_GET_PROFILE_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const EMAIL_VERIFY_REQUEST = 'EMAIL_VERIFY_REQUEST'

export const EMAIL_VERIFY_SUCCESS = 'EMAIL_VERIFY_SUCCESS'

export const EMAIL_VERIFY_FAIL = 'EMAIL_VERIFY_FAIL'

export const EMAIL_CODE_VERIFY_REQUEST = 'EMAIL_CODE_VERIFY_REQUEST'

export const EMAIL_CODE_VERIFY_SUCCESS = 'EMAIL_CODE_VERIFY_SUCCESS'

export const EMAIL_CODE_VERIFY_FAIL = 'EMAIL_CODE_VERIFY_FAIL'

