export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'

export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'

export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_GET_DETAIL_REQUEST = 'USER_GET_DETAIL_REQUEST'

export const USER_GET_DETAIL_SUCCESS = 'USER_GET_DETAIL_SUCCESS'

export const USER_GET_DETAIL_FAIL = 'USER_GET_DETAIL_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'